
# ERROR:
foo 1 do 2 end

# ERROR:
foo 1 { }