Snapshot for matching diagnosis unexpected no match (never matched)
[<MASKED TIMESTAMP>][[33mWARNING[0m]: nothing matched in ./test.py
[0m[<MASKED TIMESTAMP>][[31mERROR[0m]: test failed for rule id no-foo-unless-good on target ./test.py
--- begin input files ---
test.py
test.yaml
--- end input files ---
0/1: 1 unit tests did not pass:
--------------------------------------------------------------------------------
TODO: print(check_output_lines)
No tests for fixes found.
--------------------------------------------------------------------------------
Matching diagnosis:
./test.py: Unexpected lack of match at line 3
This line was never matched by any base pattern, nor introduced by any `focus-metavariable`.
Consider rewriting your rule to match this line.
./test.py: Unexpected lack of match at line 5
This line was never matched by any base pattern, nor introduced by any `focus-metavariable`.
Consider rewriting your rule to match this line.
[0m[33mASSERT[0m exit code
