
// ERROR:
fn foo() {
  // ERROR:
  2;
}