def foo():
    # ERROR:
    foo(1, 2)

    return 1
